name: Release Build

on:
  push:
    tags:
      - 'v*.*.*'

env:
  JAVA_VERSION: 21

  GIT_TOKEN: ${{ secrets.TOKEN }}

  NEXUS_URL: https://nexus.buecherregale.dev
  NEXUS_REPOSITORY: bin-releases
  NEXUS_USERNAME: ${{ secrets.NEXUS_USER }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASS }}

  VERSION_FILE: gradle/libs.versions.toml

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Get new Version 
        shell: bash
        run: |
          TAG_VER=${{ github.ref_name }}
          
          version="${TAG_VER#v}"
          echo "VERSION=$version" >> $GITHUB_ENV

          current_code=$(grep -E '^projectVersionCode =' "$VERSION_FILE" | sed -E 's/[^0-9]*//g')
          version_code=$((current_code + 1))

          echo "VERSION_CODE=$version_code" >> $GITHUB_ENV

          echo "New Version: $version"
          echo "New Code: $version_code"
      
      - name: Update Version 
        shell: bash
        run: |
          sed -i "s/^projectVersion = \".*\"/projectVersion = \"$VERSION\"/" "$VERSION_FILE"
          sed -i "s/^projectVersionCode = \".*\"/projectVersionCode = \"$VERSION_CODE\"/" "$VERSION_FILE"

      - name: Commit Version 
        shell: bash 
        run: |
          git config user.name "ci bot"
          git config user.email "ci@local"
          git add "$VERSION_FILE"
          git commit -m "bump version to $VERSION"
          git push http://x-access-token:${GITEA_TOKEN}@gitea:3000/${{ github.repository }}.git HEAD:main

  desktop:
    name: Desktop (${{ matrix.platform }})
    runs-on: ${{ matrix.runs-on }}
    container:
      image: ${{ matrix.image }}
    needs: update-version

    strategy:
      matrix:
        include:
          - platform: linux - debian
            runs-on: ubuntu-latest
            targets: ["Deb", "AppImage"]
            image: docker-registry.buecherregale.dev/action-runner-java-${{ env.JAVA_VERSION }}:v0.6.1
          # currently no windows & mac runner
#          - platform: windows
#            runs-on: windows-latest
#            targets: ["Msi"]
#            image: ""
#          - platform: macos
#            runs-on: macos-latest
#            targets: ["Dmg"]
#            image: ""

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Get Version
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Build all targets
        run: |
          targets='${{ toJson(matrix.targets) }}'
          echo "Building targets:"
          echo "$targets"
          for v in $(echo "$targets" | jq -r '.[]'); do
            echo "Building target: $v"
          ./gradlew :desktopApp:packageRelease$v --stacktrace
          done

      - name: Upload artifacts to Nexus 
        shell: bash
        run: |
          for dir in desktopApp/build/compose/binaries/main-release/*; do
            dirname=$(basename "$dir")

            shopt -s nullglob
            children=("$dir"/*)
            shopt -u nullglob

            count=${#children[@]}

            if (( count == 1 )) && [[ -f "${children[0]}" ]]; then
              target_path="${children[0]}"
              target_name=$(basename "$target_path")

              echo "Uploading single file artifact from $dirname: $target_name"
              curl -v --fail \
                -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
                --upload-file "$target_path" \
                "$NEXUS_URL/repository/$NEXUS_REPOSITORY/dev/buecherregale/ebook_reader/EBuecherregal/$VERSION/ebuecherregal-$VERSION.${target_name##*.}"

            else
              echo "Uploading directory artifact from $dirname"
              tar -czvf "$dirname.tar.gz" -C "$dir" .
              curl -v --fail \
                -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
                --upload-file "$dirname.tar.gz" \
                "$NEXUS_URL/repository/$NEXUS_REPOSITORY/dev/buecherregale/ebook_reader/EBuecherregal/$VERSION/ebuecherregal-$VERSION.app.tar.gz"
            fi
          done


  android:
    name: Android Release
    runs-on: ubuntu-latest
    container:
      image: docker-registry.buecherregale.dev/action-runner-android:v0.4.2
    needs: update-version

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Get Version 
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > keystore.jks 
          chmod 600 keystore.jks 

      - name: Build AAB and APK
        env: 
          ANDROID_KEYSTORE_PATH: keystore.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: ./gradlew :androidApp:bundleRelease :androidApp:assembleRelease --stacktrace

      - name: Upload APK to Nexus
        run: |
          for file in androidApp/build/outputs/apk/release/*.apk; do
            filename=$(basename "$file")
            curl -v --fail -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" --upload-file "$file" "$NEXUS_URL/repository/$NEXUS_REPOSITORY/dev/buecherregale/ebook_reader/EBuecherregal/$VERSION/ebuecherregal-$VERSION.apk"
          done

      - name: Upload AAB to Nexus
        run: |
          for file in androidApp/build/outputs/bundle/release/*.aab; do
            filename=$(basename "$file")
            curl -v --fail -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" --upload-file "$file" "$NEXUS_URL/repository/$NEXUS_REPOSITORY/dev/buecherregale/ebook_reader/EBuecherregal/$VERSION/ebuecherregal-$VERSION.aab"
          done

      - name: Cleanup
        run: rm -f keystore.jks

